map $http_x_forwarded_for $client_ip {
    default $remote_addr;
    "~."    $http_x_forwarded_for;
}

upstream backends {
    hash $client_ip consistent;
    server backend-1:80;
    server backend-2:80;
    server backend-3:80;
}

log_format lb '$upstream_addr <- $client_ip';

server {
    listen 80;
    access_log /var/log/nginx/lb.log lb;

    location / {
        proxy_pass http://backends;
        proxy_set_header Host $host;
    }
}
